### ISSUE TITLE
Suggestion: Allow site list to be passed in via stdin

### ISSUE THREAD

**Issue by ataylorme** [inclind/cantilever#1]
Thanks for making this plugin - it looks neat! As a user attached to multiple organizations and access to hundreds of sites looping through all sites I have access to takes a large amount of time.

It would be great to be able to send the results of `terminus site:list` or `terminus org:site:list` to cantilever via stdin. The [Terminus mass update plugin](https://github.com/pantheon-systems/terminus-mass-update) does this and it is really useful. 

For example, I can list sites from a specific org and filter by tag with `terminus org:site:list --tag`. That takes much less time and then cantilever could just loop through the sites I provide.

**Comment by FiLeVeR10** [comment]
@ataylorme that's what this does.

You don't need a way to send the results, this is an extension of the list plugin and does that for you based on the tags and framework you provide.

Then it will print a list of each of the site names, unless you specify a command, in which case it will run the command on each site.

The next version will have tags from the orgs available.

Watch the video linked in the readme or give it a try to see what I mean.

**Comment by FiLeVeR10** [comment]
@ataylorme This has moved over to https://github.com/terminus-plugin-project/terminus-cantilever-plugin

I did want to note, that you can currently filter by org with the `--org=orgname` variable too.

The next version is going to add an extension to `org:site:list` that will also use the org info to find sites that are tagged on the organization side. So when `--tag=sometag` is used, it will use any org data from your user account to match the sites, as well as the data for tags from the site side that it currently looks through.
